Repository raiden-network/raiden-contracts, pull requests merged in 2018-06, with the labels that each got.

#101 Raiden integration: update ChannelManager
  raiden_contracts/cm_test/test_contract_manager.py
  raiden_contracts/contract_manager.py
  raiden_contracts/tests/fixtures/token.py
  setup.py
Labels: dev: Please Review

#113 Add constants for contract and event names
  raiden_contracts/constants.py
Labels: dev: Please Review

#119 Rename TokenNetworksRegistry to TokenNetworkRegistry
  raiden_contracts/contracts/TokenNetworkRegistry.sol
  raiden_contracts/deploy/__main__.py
  raiden_contracts/tests/fixtures/contracts.py
  raiden_contracts/tests/fixtures/token_network_registry.py
  raiden_contracts/utils/config.py
Labels: dev: Please Review

#120 Use defined contract and event names in tests
  raiden_contracts/cm_test/test_contract_manager.py
  raiden_contracts/constants.py
  raiden_contracts/deploy/__main__.py
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/fixtures/contracts.py
  raiden_contracts/tests/fixtures/endpoint_registry.py
  raiden_contracts/tests/fixtures/monitoring_service.py
  raiden_contracts/tests/fixtures/raiden_service_bundle.py
  raiden_contracts/tests/fixtures/secret_registry.py
  raiden_contracts/tests/fixtures/token.py
  raiden_contracts/tests/fixtures/token_network.py
  raiden_contracts/tests/fixtures/token_network_registry.py
  raiden_contracts/tests/test_channel_close.py
  raiden_contracts/tests/test_channel_cooperative_settle.py
  raiden_contracts/tests/test_channel_deposit.py
  raiden_contracts/tests/test_channel_open.py
  raiden_contracts/tests/test_channel_settle.py
  raiden_contracts/tests/test_channel_unlock.py
  raiden_contracts/tests/test_channel_update_transfer.py
  raiden_contracts/tests/test_channel_withdraw.py
  raiden_contracts/tests/test_endpointregistry.py
  raiden_contracts/tests/test_monitoring_service.py
  raiden_contracts/tests/test_print_gas.py
  raiden_contracts/tests/test_secret_registry.py
  raiden_contracts/tests/test_token_network_registry.py
  raiden_contracts/tests/utils.py
  raiden_contracts/utils/__init__.py
  raiden_contracts/utils/config.py
Labels: dev: Please Review

#114 Fix settlement calculations
  raiden_contracts/contracts/TokenNetwork.sol
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/fixtures/channel_test_values.py
  raiden_contracts/tests/test_channel_settle.py
  raiden_contracts/tests/utils.py
Labels: bug, dev: Please Review, security, testing

#124 Add channel deposit overflow check & test
  raiden_contracts/contracts/TokenNetwork.sol
  raiden_contracts/contracts/test/CustomToken.sol
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/test_channel_deposit.py
  raiden_contracts/tests/test_monitoring_service.py
  raiden_contracts/tests/test_token.py
Labels: dev: Please Review

#123 Fix settlement overflow on transferred amount
  raiden_contracts/contracts/TokenNetwork.sol
  raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/fixtures/channel_test_values.py
  raiden_contracts/tests/test_channel_settle.py
  raiden_contracts/tests/test_channel_unlock.py
  raiden_contracts/tests/test_monitoring_service.py
  raiden_contracts/tests/test_print_gas.py
Labels: dev: Please Review

#138 Include secret in SecretRevealed event
  raiden_contracts/contracts/SecretRegistry.sol
  raiden_contracts/tests/test_secret_registry.py
  raiden_contracts/utils/events.py
Labels: dev: Please Review

#130 More flake8 plugins
  raiden_contracts/cm_test/test_contract_manager.py
  raiden_contracts/contract_manager.py
  raiden_contracts/deploy/__main__.py
  raiden_contracts/tests/fixtures/channel_test_values.py
  raiden_contracts/tests/fixtures/contracts.py
  raiden_contracts/tests/fixtures/monitoring_service.py
  raiden_contracts/tests/fixtures/raiden_service_bundle.py
  raiden_contracts/tests/fixtures/test_contracts.py
  raiden_contracts/tests/fixtures/token_network.py
  raiden_contracts/tests/fixtures/token_network_registry.py
  raiden_contracts/tests/fixtures/utils.py
  raiden_contracts/tests/test_channel_close.py
  raiden_contracts/tests/test_channel_cooperative_settle.py
  raiden_contracts/tests/test_channel_deposit.py
  raiden_contracts/tests/test_channel_open.py
  raiden_contracts/tests/test_channel_settle.py
  raiden_contracts/tests/test_channel_unlock.py
  raiden_contracts/tests/test_channel_update_transfer.py
  raiden_contracts/tests/test_channel_withdraw.py
  raiden_contracts/tests/test_monitoring_service.py
  raiden_contracts/tests/test_print_gas.py
  raiden_contracts/tests/test_recover_from_signature.py
  raiden_contracts/tests/test_secret_registry.py
  raiden_contracts/tests/test_token_network.py
  raiden_contracts/tests/test_token_network_registry.py
  raiden_contracts/tests/utils.py
  raiden_contracts/utils/logs.py
  raiden_contracts/utils/sign.py
  requirements-dev.txt
Labels: dev: Please Review

#134 unit tests for TokenNetwork internals
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/test_channel_withdraw.py
  raiden_contracts/tests/unit/__init__.py
  raiden_contracts/tests/unit/test_settle_timeout_invariant.py
  raiden_contracts/tests/unit/test_unit_internals.py
Labels: dev: Please Review, dev: Work In Progress

#155 Use same style for open channel state as the other states
  raiden_contracts/constants.py
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/test_channel_close.py
  raiden_contracts/tests/test_channel_open.py
  raiden_contracts/tests/test_channel_update_transfer.py
  raiden_contracts/tests/test_channel_withdraw.py
Labels: dev: Please Review

#154 Resolve missing unlock tests from raiden/[...]/test_withdraw.
  raiden_contracts/tests/test_channel_unlock.py
  raiden_contracts/tests/unit/test_recover_from_signature.py
Labels: dev: Please Review

#160 Fix locksroot & locked amount storage after balance proofs are updated
  raiden_contracts/contracts/TokenNetwork.sol
  raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
  raiden_contracts/tests/fixtures/channel.py
  raiden_contracts/tests/test_channel_unlock.py
Labels: dev: Please Review
