Repository raiden-network/raiden-contracts, pull requests merged in 2019-02, with the labels that each got.

#513 More useful verify_deployed_contract() and fewer lines around its usage
  raiden_contracts/deploy/__main__.py
Labels: refactoring

#540 Refactor similar lines deploying contracts
  raiden_contracts/deploy/__main__.py
Labels: dev: Please Review

#539 Specify the exact solc version
  raiden_contracts/contract_manager.py
  raiden_contracts/contracts/EndpointRegistry.sol
  raiden_contracts/contracts/SecretRegistry.sol
  raiden_contracts/contracts/Token.sol
  raiden_contracts/contracts/TokenNetwork.sol
  raiden_contracts/contracts/TokenNetworkRegistry.sol
  raiden_contracts/contracts/Utils.sol
  raiden_contracts/contracts/lib/ECVerify.sol
  raiden_contracts/contracts/services/MonitoringService.sol
  raiden_contracts/contracts/services/OneToN.sol
  raiden_contracts/contracts/services/ServiceRegistry.sol
  raiden_contracts/contracts/services/UserDeposit.sol
  raiden_contracts/contracts/test/CustomToken.sol
  raiden_contracts/contracts/test/HumanStandardToken.sol
  raiden_contracts/contracts/test/SignatureVerifyTest.sol
  raiden_contracts/contracts/test/StandardToken.sol
  raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
  raiden_contracts/contracts/test/UDCTransfer.sol
  raiden_contracts/data/contracts.json
Labels: dev: Please Review

#592 fix typo and add some view modifiers
  raiden_contracts/contracts/services/MonitoringService.sol
  raiden_contracts/contracts/services/ServiceRegistry.sol
  raiden_contracts/contracts/services/UserDeposit.sol
  raiden_contracts/data/contracts.json
Labels: dev: Please Review

#594 README only three contract_versions are available
  README.rst
  raiden_contracts/tests/test_contracts_compilation.py
Labels: dev: Please Review

#617 Use Mustache to generate limited and unlimited versions
  .gitignore
  .travis.yml
  CHANGELOG.md
  Makefile
  README.rst
  raiden_contracts/contract_manager.py
  raiden_contracts/contracts_template/__init__.py
  raiden_contracts/contracts_template/lib/ECVerify.sol
  raiden_contracts/contracts_template/raiden/EndpointRegistry.sol
  raiden_contracts/contracts_template/raiden/SecretRegistry.sol
  raiden_contracts/contracts_template/raiden/Token.sol
  raiden_contracts/contracts_template/raiden/TokenNetwork.sol
  raiden_contracts/contracts_template/raiden/TokenNetworkRegistry.sol
  raiden_contracts/contracts_template/raiden/Utils.sol
  raiden_contracts/contracts_template/services/MonitoringService.sol
  raiden_contracts/contracts_template/services/OneToN.sol
  raiden_contracts/contracts_template/services/ServiceRegistry.sol
  raiden_contracts/contracts_template/services/UserDeposit.sol
  raiden_contracts/contracts_template/test/CustomToken.sol
  raiden_contracts/contracts_template/test/HumanStandardToken.sol
  raiden_contracts/contracts_template/test/MonitoringServiceInternalsTest.sol
  raiden_contracts/contracts_template/test/SignatureVerifyTest.sol
  raiden_contracts/contracts_template/test/StandardToken.sol
  raiden_contracts/contracts_template/test/TokenNetworkInternalsTest.sol
  raiden_contracts/contracts_template/test/UDCTransfer.sol
  raiden_contracts/contracts_template/test/__init__.py
  raiden_contracts/data/contracts.json
  raiden_contracts/data_unlimited/contracts.json
  raiden_contracts/deploy/__main__.py
  raiden_contracts/deploy/etherscan_verify.py
  raiden_contracts/tests/deprecation_switch_testnet.py
  raiden_contracts/tests/test_deploy_script.py
  requirements-dev.txt
  setup.py
Labels: dev: Please Review

#635 Fix version numbers caused by Mustache typo
  raiden_contracts/contract_manager.py
  raiden_contracts/data/gas.json
  raiden_contracts/data_unlimited/contracts.json
  raiden_contracts/data_unlimited/source/raiden/EndpointRegistry.sol
  raiden_contracts/data_unlimited/source/raiden/SecretRegistry.sol
  raiden_contracts/data_unlimited/source/raiden/TokenNetwork.sol
  raiden_contracts/data_unlimited/source/raiden/TokenNetworkRegistry.sol
  raiden_contracts/data_unlimited/source/raiden/Utils.sol
  raiden_contracts/data_unlimited/source/services/MonitoringService.sol
  raiden_contracts/data_unlimited/source/services/OneToN.sol
  raiden_contracts/data_unlimited/source/services/ServiceRegistry.sol
  raiden_contracts/data_unlimited/source/services/UserDeposit.sol
  raiden_contracts/deploy/__main__.py
  raiden_contracts/tests/deprecation_switch_testnet.py
  raiden_contracts/tests/test_deploy_script.py
  setup.py
Labels: P1, bug
